export enum DeliveryProduct {
  FAST = 'fast',
  CHEAP = 'cheap',
  BULK = 'bulk',
  PREMIUM = 'premium',
  REGISTERED = 'registered',
  ATPOST_ECONOMY = 'atpost_economy',
  ATPOST_PRIORITY = 'atpost_priority',
  POSTAG_A = 'postag_a',
  POSTAG_B = 'postag_b',
  POSTAG_B2 = 'postag_b2',
  POSTAG_REGISTERED = 'postag_registered',
  POSTAG_APLUS = 'postag_aplus',
  DPAG_STANDARD = 'dpag_standard',
  DPAG_ECONOMY = 'dpag_economy',
  INDPOST_MAIL = 'indpost_mail',
  INDPOST_SPEEDMAIL = 'indpost_speedmail',
  NLPOST_PRIORITY = 'nlpost_priority',
  DHL_EUROPE_PRIORITY = 'dhl_europe_priority',
  DHL_WORLD_PRIORITY = 'dhl_world_priority',
}
